package com.example.drivinglicence.utils

val TITLE_TOOLBAR = "TITLE_TOOLBAR"
val QUESTION = "QUESTION"
val QUESTIONS = "QUESTIONS"
val ANSWERS = "ANSWERS"
val FLAG = "FLAG"
val IS_SECOND = "IS_SECOND"
val LICENSE = "LICENSE"
val POSITION = "POSITION"
val LIST_ANSWERS = "LIST_ANSWERS"